### ISSUE TITLE
Add description to plugin in the installed plugins screen.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/caldera-forms-pro#3]
Hey Josh

I will go ahead and add issues here of whatever I notice that I believe should be looked at.
Add a description to the plugin so that it shows up above the version number.

![screen shot 2017-07-10 at 21 36 16](https://user-images.githubusercontent.com/5323259/28036230-d56e6c26-65b7-11e7-906b-fd2daacd6be1.png)

**Comment by Shelob9** [comment]
Close via e3a4a64012046d09f8f8a5b93732ed3d3193d9fc
