### ISSUE TITLE
UI setting for options level and disable

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/caldera-forms-pro#51]
related #50

**Comment by Shelob9** [comment]
1. Add UI option in main settings screen
2. Add handling in settings class for storing and getting this.
3. Add handling in REST API callback for saving this setting
4. Use method created in item 2, to set default minimum log level on the filter for that.

**Comment by New0** [comment]
Moved to https://github.com/CalderaWP/Caldera-Forms/issues/2200
