### ISSUE TITLE
Prevent loading if CF is too old.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/caldera-forms-pro#59]

**Comment by Shelob9** [comment]
Close via 25b81f1

**Comment by Shelob9** [comment]
I am reopening as @New0 can confirm this prevents load with 1.5.6.x active. I think that's beacuse plugins are loaded in alphabetical order of basename. I move activation to plugins_loaded:5 and put it in a PR.

**Comment by New0** [comment]
Closed by PR #60
