### ISSUE TITLE
Private key vs Secret Key

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/caldera-forms-pro#7]
On the confirmation page:
https://calderaforms.com/checkout/purchase-confirmation/?payment-confirmation=paypal&payment-id=69659

![screen shot 2017-07-10 at 21 52 09](https://user-images.githubusercontent.com/5323259/28036928-19950caa-65ba-11e7-92ac-16cafb58a263.png)

Public Key and Private Key

On the backend page:

![screen shot 2017-07-10 at 21 53 08](https://user-images.githubusercontent.com/5323259/28036957-2dc404f6-65ba-11e7-9603-cc02abd40c04.png)

API Key
Your Caldera Forms Pro API Public Key

API Secret
Your Caldera Forms Pro API Secret Key

Keep the language identical: Either Private or Secret.

**Comment by Shelob9** [comment]
Close via https://gitlab.com/caldera-labs/taco/commit/af0ca7e741596e1fb91337c4203b58d7b586611b
